from __future__ import annotations

from pathlib import Path
from typing import Any


CARD_SECTIONS = [
    "Paper",
    "World",
    "Institution",
    "Agent type",
    "Theoretical benchmark",
    "Learning setup",
    "Metrics",
    "Main result",
    "What they prove",
    "What they only simulate",
    "What they do NOT test",
    "What we need to reproduce",
    "How our project differs",
]


def slugify(value: str) -> str:
    slug = "".join(c.lower() if c.isalnum() else "_" for c in value)
    return "_".join(part for part in slug.split("_") if part)[:90] or "untitled"


def make_blank_card(paper: dict[str, Any], out_dir: Path) -> Path:
    out_dir.mkdir(parents=True, exist_ok=True)
    title = paper.get("title") or "Untitled"
    year = paper.get("year") or "unknown"
    path = out_dir / f"{year}_{slugify(title)}.md"
    if path.exists():
        return path
    lines = [
        f"# {title}",
        "",
        "<!-- Generated by tools.theory_scout. Fill TODO fields from the paper, not from memory. -->",
        "",
        f"Source: {paper.get('source')}",
        f"Source ID: {paper.get('source_id')}",
        f"Year: {paper.get('year')}",
        f"Authors: {', '.join(paper.get('authors') or [])}",
        f"DOI: {paper.get('doi')}",
        f"URL: {paper.get('url')}",
        f"PDF: {paper.get('pdf_url')}",
        f"World: {paper.get('world')}",
        f"Query: {paper.get('query')}",
        "",
    ]
    for section in CARD_SECTIONS:
        default = title if section == "Paper" else paper.get("world") if section == "World" else "TODO"
        lines.extend([f"## {section}", "", str(default), ""])
    path.write_text("\n".join(lines), encoding="utf-8")
    return path
