from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class ObligationTemplate:
    institution: str
    agent_type: str
    theoretical_benchmark: str
    learning_setup: str
    metrics: str
    what_we_need_to_reproduce: str
    how_our_project_differs: str
    implementation_obligations: str
    metrics_to_compare_in_our_repo: str
    failure_modes_to_audit: str
    project_code_comparison: str

    def to_fields(self, record: dict[str, Any]) -> dict[str, str]:
        values = {
            "title": str(record.get("title") or "this paper"),
            "world": str(record.get("world") or "unknown_world"),
            "institution": str(record.get("institution") or "unknown institution"),
            "mind": str(record.get("mind") or "unknown mind"),
            "theory_obligation": str(record.get("theory_obligation") or "No project obligation supplied."),
            "code_result_check": str(record.get("code_result_check") or "No repo evidence supplied."),
            "why_it_matters": str(record.get("why_it_matters") or ""),
        }
        return {
            key: value.format(**values)
            for key, value in {
                "institution": self.institution,
                "agent_type": self.agent_type,
                "theoretical_benchmark": self.theoretical_benchmark,
                "learning_setup": self.learning_setup,
                "metrics": self.metrics,
                "what_we_need_to_reproduce": self.what_we_need_to_reproduce,
                "how_our_project_differs": self.how_our_project_differs,
                "implementation_obligations": self.implementation_obligations,
                "metrics_to_compare_in_our_repo": self.metrics_to_compare_in_our_repo,
                "failure_modes_to_audit": self.failure_modes_to_audit,
                "project_code_comparison": self.project_code_comparison,
            }.items()
        }


def _method_template(
    *,
    agent_type: str,
    theoretical_benchmark: str,
    learning_setup: str,
    metrics: str,
    reproduce: str,
    differs: str,
    obligations: str,
    repo_metrics: str,
    failures: str,
    comparison: str,
) -> ObligationTemplate:
    return ObligationTemplate(
        institution="Not applicable: method paper.",
        agent_type=agent_type,
        theoretical_benchmark=theoretical_benchmark,
        learning_setup=learning_setup,
        metrics=metrics,
        what_we_need_to_reproduce=reproduce,
        how_our_project_differs=differs,
        implementation_obligations=obligations,
        metrics_to_compare_in_our_repo=repo_metrics,
        failure_modes_to_audit=failures,
        project_code_comparison=comparison,
    )


def _economic_template(
    *,
    institution: str,
    agent_type: str,
    theoretical_benchmark: str,
    learning_setup: str,
    metrics: str,
    reproduce: str,
    differs: str,
    obligations: str,
    repo_metrics: str,
    failures: str,
    comparison: str,
) -> ObligationTemplate:
    return ObligationTemplate(
        institution=institution,
        agent_type=agent_type,
        theoretical_benchmark=theoretical_benchmark,
        learning_setup=learning_setup,
        metrics=metrics,
        what_we_need_to_reproduce=reproduce,
        how_our_project_differs=differs,
        implementation_obligations=obligations,
        metrics_to_compare_in_our_repo=repo_metrics,
        failure_modes_to_audit=failures,
        project_code_comparison=comparison,
    )


ROLE_TEMPLATES: dict[str, ObligationTemplate] = {
    "tabular_rl": _method_template(
        agent_type="Tabular temporal-difference control / Q-learning.",
        theoretical_benchmark="Algorithmic benchmark: Bellman optimality control with a discrete state-action value table.",
        learning_setup="Discrete observations, discrete actions, epsilon-greedy exploration, TD target, learning rate, discount factor, and repeated online updates.",
        metrics="Repo-side behavioral metrics by world plus validation that the same tabular update rule runs unchanged across worlds.",
        reproduce="Reproduce the method-level Q-learning obligation inside this repo: explicit discrete state/action encoding, Q-table shape, TD target, epsilon schedule, and cross-world smoke/full evidence from {code_result_check}.",
        differs="The paper establishes a general tabular RL algorithm. This repo uses Q-learning as a controlled low-capability baseline for economic worlds rather than as a theorem-reproduction exercise.",
        obligations="Discrete observation encoder; finite action set; Q-table indexed by the declared state shape; epsilon-greedy action selection; TD target reward + gamma max_a Q(s',a); no world-specific changes to the Agent interface.",
        repo_metrics="minds/q_learning.py implementation; tests that QLearningMind runs on Pricing Arena, Resource Island, Auction House, Public Goods, and Labor Market; full-run welfare/collusion/sustainability/stability outputs where available.",
        failures="Hidden world-specific Q-learning forks; state encoders that omit economically necessary information; claiming interface generality without cross-world tests; interpreting behavior without reporting state/action discretization.",
        comparison="Compare {title} to minds/q_learning.py and the cross-world Q-learning outputs. The repo satisfies the method obligation if the same Agent update rule runs over each world's explicit discrete observation shape; it does not try to reproduce a single canonical benchmark task.",
    ),
    "deep_rl": _method_template(
        agent_type="Deep Q-network / value-based neural RL.",
        theoretical_benchmark="Method benchmark: neural Q-learning with replay, a target network, and TD-error minimization.",
        learning_setup="Structured observations encoded as vectors, epsilon-greedy exploration, replay buffer sampling, target-network bootstrapping, and a neural Q function.",
        metrics="Repo-side: finite task metrics, smoke/full outputs, DQN-vs-tabular comparisons, and tests for replay/target-network behavior.",
        reproduce="Do not reproduce Atari for this thesis. Reproduce the DQN method obligation: neural Q-values, target network, replay buffer, agent-local randomness, TD/Huber loss, and cross-world validation from {code_result_check}.",
        differs="The paper validates DQN on high-dimensional game inputs. This repo adapts the DQN update structure to structured economic observations and tests whether it changes economic behavior relative to tabular Q-learning.",
        obligations="Fixed-width feature encoder; Q-network; target Q-network; replay memory; epsilon-greedy exploration from an agent-local RNG; TD/Huber loss; target-network sync; finite-value guards.",
        repo_metrics="minds/deep_rl/torch_dqn_mind.py; test_phase3_deep_rl.py; Resource Island Phase 3 tests; outputs/phase3_full/mind_comparison.csv; cross-world ladder outputs.",
        failures="DQN label without replay or target network; global shared RNG that collapses independent agents; smoke-only evidence; comparing DQN to tabular Q without confirming the observation encoder is meaningful.",
        comparison="Compare {title} to minds/deep_rl/torch_dqn_mind.py and {code_result_check}. The repo should claim DQN as an adapted method baseline, not as an Atari reproduction.",
    ),
    "policy_gradient": _method_template(
        agent_type="On-policy actor-critic / PPO.",
        theoretical_benchmark="No economic-theory benchmark. The method benchmark is empirical comparison against other online policy-gradient methods on standard RL tasks.",
        learning_setup="PPO alternates on-policy rollout collection with minibatch epochs over a clipped surrogate objective, value-function learning, advantage estimates, and entropy regularization.",
        metrics="Paper-side: average episodic return, learning curves, sample complexity, simplicity, and wall-time. Repo-side: world metrics and finite-run validation outputs.",
        reproduce="Do not reproduce Atari/MuJoCo for this thesis. Reproduce the method-level obligation: categorical discrete policy, clipped surrogate updates, old log probabilities, advantage estimation, value loss, entropy bonus, and repeated minibatch epochs, then compare PPO against Q-learning/DQN/MARL inside the artificial-economies worlds.",
        differs="The paper validates PPO as a general RL algorithm on standard control/game benchmarks. This repo adapts PPO to structured observations and discrete economic actions, then asks whether its learned economic behavior differs from tabular Q-learning, DQN, independent-DQN, and centralized-critic agents.",
        obligations="Categorical discrete policy; separate value function; stored old log probabilities; GAE-style advantage computation; clipped surrogate probability-ratio objective; value loss; entropy bonus; minibatch epochs over on-policy rollout batches.",
        repo_metrics="minds/deep_rl/torch_ppo_mind.py; test_phase3_deep_rl.py; outputs/phase3_full/mind_comparison.csv; Resource Island and other cross-world mind-comparison tables.",
        failures="PPO label without clipped old-policy ratio; stale off-policy replay used as PPO; missing value baseline or advantage estimates; no entropy/value terms; only smoke tests without full-run comparison.",
        comparison="minds/deep_rl/torch_ppo_mind.py implements a structured-observation discrete PPO mind with Categorical actions, policy/value networks, rollout storage, GAE parameters, clipped surrogate objective, value loss, entropy coefficient, and minibatch epochs. That satisfies the thesis method obligation but does not reproduce the original continuous-control, Atari, sample-complexity, or wall-time benchmark suite.",
    ),
    "independent_marl": _method_template(
        agent_type="Independent multi-agent Q-learning / independent DQN learners.",
        theoretical_benchmark="MARL baseline benchmark: each agent learns its own policy while treating other learners as part of the environment.",
        learning_setup="Separate learner per agent, separate exploration and replay streams, no shared parameters, and shared environment feedback only through interaction.",
        metrics="Behavioral divergence from single-agent/shared baselines, coordination outcomes, welfare/exploitability/stability, and tests for seed/replay independence.",
        reproduce="Reproduce independent learning as a genuine MARL condition: no shared network, no shared replay buffer, no shared exploration stream, and no aliasing with plain DQN. Evidence must come from {code_result_check}.",
        differs="The paper contrasts independent and cooperative multi-agent learning. This repo uses independent-DQN as a capability-ladder condition and must show it is not just DQN duplicated under the same random stream.",
        obligations="Per-agent learner objects; decorrelated SeedSequence child streams; per-agent replay buffers; per-agent epsilon-greedy RNGs; separate network initialization; tests that Q-values/rollouts diverge under one base seed.",
        repo_metrics="minds/marl/independent_learners.py; decorrelation tests; fixed independent-DQN full outputs in Pricing Arena and Resource Island; cross-world ladder comparison tables.",
        failures="Subclass alias of DQN; seed + index streams that still collapse under symmetry; shared replay/global np.random/random/torch state; reporting independent-DQN rows that are bit-identical to DQN.",
        comparison="Compare {title} to minds/marl/independent_learners.py and {code_result_check}. The repo obligation is satisfied only if independent-DQN remains a distinct condition in tests, smoke gates, and full tables.",
    ),
    "centralized_critic": _method_template(
        agent_type="Centralized-training/decentralized-execution actor-critic MARL.",
        theoretical_benchmark="MARL benchmark: decentralized actors with a critic that can condition on broader joint or centralized information during training.",
        learning_setup="Actor policies act from local observations; the critic/value estimate uses centralized context where available; evaluation distinguishes centralized training from decentralized execution.",
        metrics="World-level welfare/stability/exploitability plus comparison against DQN, PPO, and independent-DQN; special attention to asymmetric-agent worlds.",
        reproduce="Reproduce the interface-level obligation: centralized critic must be structurally distinct from independent learners, handle fixed observation dimensions, and either support or explicitly reject asymmetric-agent worlds. Evidence: {code_result_check}.",
        differs="The paper studies mixed cooperative-competitive MARL. This repo adapts the pattern to economic worlds; Labor Market asymmetry is a real stress test rather than a minor config change.",
        obligations="Decentralized actor action selection; centralized value/critic input when configured; consistent obs_dim/action_dim handling; no accidental fallback to independent DQN; explicit validation in symmetric and asymmetric worlds.",
        repo_metrics="minds/marl/centralized_critic.py; cross-world P.6 smoke/full outputs; synthesis tables separating centralized-critic from independent-DQN.",
        failures="Centralized critic implemented as a label around independent learners; critic sees inconsistent dimensions; asymmetric agents forced through a symmetric interface; smoke validation without full-run interpretation.",
        comparison="Compare {title} to minds/marl/centralized_critic.py and {code_result_check}. The repo should report centralized-critic as a separate MARL scaffold, with limitations where the world does not provide the centralized information assumed by the method.",
    ),
    "classical_io": _economic_template(
        institution="Pricing game baseline with no regulatory institution.",
        agent_type="Strategic firms / pricing agents.",
        theoretical_benchmark="Static Bertrand/Nash pricing and joint-profit/collusive price benchmarks.",
        learning_setup="Repeated duopoly pricing with learned policies compared against static one-shot references.",
        metrics="Average price, welfare/profit, Nash and joint-profit benchmark gaps, price/profit collusion indices.",
        reproduce="Reproduce the IO benchmark role: every Pricing Arena result needs Nash/Bertrand and joint-profit reference lines before learned prices are interpreted.",
        differs="The book gives classical theory; the repo tests learned behavior under repeated interaction and institutions. Theory is the reference scale, not a claim that agents solve the static model.",
        obligations="Compute static Nash price pairs; compute symmetric joint-profit price; expose benchmark columns in summaries; distinguish competitive benchmark from collusive benchmark.",
        repo_metrics="worlds/pricing_arena/benchmarks.py; outputs/full_v0_multiseed/mechanism_rankings.csv; outputs/phase3_full/mind_comparison.csv.",
        failures="Calling high prices collusion without a Nash/joint-profit scale; mixing price-normalized and profit-normalized indices; comparing minds without fixed benchmark definitions.",
        comparison="Compare {title} to worlds/pricing_arena/benchmarks.py and the pricing outputs. The repo is strongest where learned policies are reported relative to Nash and joint-profit references.",
    ),
    "algorithmic_collusion": _economic_template(
        institution="Repeated pricing with no institution or with regulatory variants.",
        agent_type="Q-learning pricing firms and higher-capability RL pricing agents.",
        theoretical_benchmark="Profit-normalized collusion relative to competitive and monopoly/joint-profit benchmarks.",
        learning_setup="Repeated pricing game with learning agents, final-window behavior, and institution comparisons.",
        metrics="Profit-normalized collusion index, price proxy collusion index, average price, total profit, welfare, exploitability.",
        reproduce="Report profit-normalized collusion, not only a price proxy, and interpret price-cap results using both price and profit channels.",
        differs="The paper anchors algorithmic collusion for Q-learning. This repo extends the question across DQN, PPO, independent-DQN, centralized critic, and institution variants.",
        obligations="Profit benchmark computation; profit_collusion_index_mean in comparison tables; exploitability protocol; capability-ladder table; mechanism-specific diagnostics.",
        repo_metrics="outputs/phase3_full/mind_comparison.csv; outputs/v1_exploitability/summary_aggregate.csv; build_combined_table.py.",
        failures="Using only price-normalized collusion; treating capped prices as automatically non-collusive; ignoring quantity/profit channel; failing to separate exploitability from collusion.",
        comparison="Compare {title} to outputs/phase3_full/mind_comparison.csv. The repo now reports both price and profit collusion, making the DQN price-cap profit channel thesis-facing rather than a metric artifact.",
    ),
    "monitoring": _economic_template(
        institution="Demand shock / imperfect monitoring variant.",
        agent_type="Learning pricing firms.",
        theoretical_benchmark="Collusion under noisy monitoring and punishment/price-war dynamics.",
        learning_setup="Repeated pricing where the signal mapping from actions to rewards is noisier or institutionally perturbed.",
        metrics="Collusion, price dispersion, profit, exploitability, robustness under shock.",
        reproduce="Treat demand shocks as an information/monitoring change and compare whether collusion/exploitability survive under the shock.",
        differs="The paper focuses on imperfect monitoring in algorithmic collusion. This repo uses the demand_shock mechanism as a coarse monitoring/environment stress test.",
        obligations="Explicit demand_shock mechanism; fixed seeds; same metrics as baseline pricing; robustness comparison against no-institution pricing.",
        repo_metrics="demand_shock rows in outputs/phase3_full/mind_comparison.csv and exploitability summaries.",
        failures="Calling random noise an institution without documenting the information channel; comparing shocked and unshocked runs with different training protocols; ignoring variance/dispersion.",
        comparison="Compare {title} to the demand_shock mechanism and pricing outputs. The repo should describe this as a monitoring stress test, not as a full reproduction of the paper's model.",
    ),
    "algorithm_design": _economic_template(
        institution="Pricing algorithm design / learning-protocol variation.",
        agent_type="Q-learning and neural pricing algorithms.",
        theoretical_benchmark="Learning-protocol changes can shift pricing outcomes between competitive and supra-competitive regimes.",
        learning_setup="Capability ladder over tabular Q, DQN, PPO, independent-DQN, and centralized critic under matched pricing institutions.",
        metrics="Collusion indices, exploitability, price/profit/welfare, price dispersion, and mind-by-institution effects.",
        reproduce="Interpret capability differences as algorithm-design effects and show matched comparisons across minds and institutions.",
        differs="The paper studies algorithm-design choices in pricing. This repo generalizes that discipline into a cross-world capability ladder.",
        obligations="Same institution set across minds; full n=20 outputs; fixed independent-DQN replacement; synthesis table separating capability effects from mechanism effects.",
        repo_metrics="outputs/phase3_full/mind_comparison.csv; build_world_mind_comparison.py; build_cross_world_synthesis.py.",
        failures="Attributing differences to economics when training protocol changed; keeping alias mind rows; failing to report uncertainty/paired effects.",
        comparison="Compare {title} to the Phase 3 ladder outputs. The repo's contribution is not just another pricing run; it tests whether algorithm capability changes institution robustness.",
    ),
    "sequential_pricing": _economic_template(
        institution="Pricing timing/protocol choice.",
        agent_type="Q-learning pricing firms.",
        theoretical_benchmark="Sequential versus simultaneous pricing changes strategic observability and punishment opportunities.",
        learning_setup="Repeated pricing with a specific move protocol; interpretation depends on timing.",
        metrics="Average prices, profit, collusion index, learning dynamics.",
        reproduce="State explicitly that Pricing Arena uses simultaneous action semantics unless a sequential variant is implemented.",
        differs="The paper studies sequential pricing. This repo's current pricing world is simultaneous, so the paper is a timing caveat and future-ablation anchor.",
        obligations="Document step timing; avoid overclaiming sequential-collusion comparability; add sequential ablation only if needed for paper scope.",
        repo_metrics="worlds/pricing_arena/env.py; Pricing Arena design notes; Phase 3 pricing outputs.",
        failures="Citing sequential-pricing evidence as if the repo used sequential timing; hiding timing differences in the methods section.",
        comparison="Compare {title} to Pricing Arena step semantics. The repo can cite this as related evidence, but must state the timing mismatch clearly.",
    ),
    "deep_rl_pricing": _economic_template(
        institution="Repeated pricing with neural RL agents.",
        agent_type="DQN/PPO/deep MARL pricing agents.",
        theoretical_benchmark="Neural agents may reproduce, attenuate, or alter tabular algorithmic collusion patterns.",
        learning_setup="Deep RL pricing agents trained under repeated interaction and compared to tabular baselines.",
        metrics="Price/profit collusion, average price, profit, welfare, exploitability, dispersion.",
        reproduce="Compare whether DQN/PPO/MARL reproduce or break tabular collusion patterns under each institution.",
        differs="The paper is a deep-RL pricing anchor. This repo adds explicit institution robustness, exploitability, and cross-world synthesis.",
        obligations="Full neural mind table; profit-normalized collusion; price-cap diagnosis; DQN/PPO/independent-DQN/centralized-critic separated.",
        repo_metrics="outputs/phase3_full/mind_comparison.csv; outputs/phase3_full/validation_report.json.",
        failures="Conflating DQN and independent-DQN; no profit metric; smoke-scale results treated as final; no exploitability comparison.",
        comparison="Compare {title} to the Phase 3 full table. The repo should use it to justify the neural pricing ladder and then foreground its own price-cap quantity/profit result.",
    ),
    "truthful_second_price": _economic_template(
        institution="Second-price / Vickrey auction.",
        agent_type="Private-value bidders or learning bidder agents.",
        theoretical_benchmark="Truthful bidding is weakly dominant in a private-value second-price auction; efficient allocation should follow truthful reports.",
        learning_setup="Repeated private value draws with learned bidding policies compared against truthful bidding.",
        metrics="Revenue, allocative efficiency, bidder surplus, welfare, truthful-bid regret, overbidding/underbidding rates.",
        reproduce="Second-price benchmarks must include truthful bidding, allocative efficiency, and regret/IC proxy, not only bidder reward.",
        differs="The paper is one-shot auction theory. This repo studies whether learning bidders approach or fail that benchmark over repeated draws.",
        obligations="Truthful bid benchmark; deterministic tie-breaking; payment equals second price subject to reserve; ex-post regret; bid-curve extraction.",
        repo_metrics="worlds/auction_house/benchmarks.py; outputs/auction_house_full/summary_aggregate.csv; learned bid curves.",
        failures="Interpreting revenue without efficiency/regret; no truthful reference; learned bids below benchmark but still called Vickrey behavior.",
        comparison="Compare {title} to Auction House second_price outputs. The repo is coherent only if second-price learning is judged against truthfulness, efficiency, and regret.",
    ),
    "optimal_auction": _economic_template(
        institution="Reserve-price / revenue-optimal auction variant.",
        agent_type="Private-value bidders and seller mechanism.",
        theoretical_benchmark="Myerson-style revenue maximization and reserve-price tradeoff under independent private values.",
        learning_setup="Repeated auctions under reserve/no-sale rules with learned bidder strategies.",
        metrics="Seller revenue, allocative efficiency, welfare, no-sale rate, bidder surplus, regret.",
        reproduce="Reserve-price scenarios must report the revenue/efficiency/welfare tradeoff against no-reserve second price.",
        differs="The paper characterizes optimal mechanisms. This repo implements simple reserve variants and learned bidder responses, not learned optimal mechanism design.",
        obligations="Reserve/no-sale handling; revenue benchmark; welfare loss accounting; efficiency comparison; regret under reserve.",
        repo_metrics="second_price_reserve scenario; worlds/auction_house/benchmarks.py; outputs/auction_house_full.",
        failures="Calling a reserve setting optimal without distribution assumptions; ignoring welfare/no-sale cost; not comparing to no-reserve baseline.",
        comparison="Compare {title} to the Auction House reserve scenario. The repo should frame reserves as a benchmarked design variant, not as full Myerson optimal-auction recovery.",
    ),
    "learned_auction_design": _economic_template(
        institution="Learned auction design / RegretNet-style mechanism learning.",
        agent_type="Neural mechanism designer and strategic bidders in prior work; bidder learners in this repo.",
        theoretical_benchmark="Revenue maximization subject to incentive compatibility/regret and individual-rationality constraints.",
        learning_setup="Differentiable mechanism learning in the paper; repeated learned bidder behavior in this repo.",
        metrics="Revenue, regret/IC violation, allocative efficiency, bidder surplus, generalization.",
        reproduce="Auction House must include regret or incentive-compatibility proxies, revenue, allocative efficiency, and truthful/strategic benchmarks.",
        differs="The paper learns mechanisms. This repo currently learns bidder behavior under fixed mechanisms, so it can borrow the metric discipline but not claim mechanism-learning equivalence.",
        obligations="Ex-post regret; revenue; allocative efficiency; benchmark bid curves; future exploitability under learned misreports if mechanism learning is added.",
        repo_metrics="Auction House regret, revenue, efficiency, over/underbidding diagnostics; outputs/auction_house_full; variant smoke outputs.",
        failures="Evaluating auctions only by bidder reward; omitting IC/regret; claiming RegretNet-style contribution without learning the mechanism; no generalization check.",
        comparison="Compare {title} to worlds/auction_house/benchmarks.py and Auction House outputs. The repo should cite it as a metric obligation for auction learning, while stating that mechanisms are fixed rather than learned.",
    ),
    "ai_auction_design": _economic_template(
        institution="First-price and second-price auction formats under learning agents.",
        agent_type="Q-learning or algorithmic bidders.",
        theoretical_benchmark="Auction format changes learned bidding, bid shading, revenue, and efficiency.",
        learning_setup="Repeated auctions where agents learn bids from private-value observations.",
        metrics="Revenue, underbidding/bid shading, efficiency, surplus, regret, learned bid curves.",
        reproduce="Compare first-price bid shading and second-price truthfulness-like behavior using learned bid curves and regret.",
        differs="The paper studies AI and auction design. This repo implements a controlled Auction House world and validates mechanics before cross-mind passes.",
        obligations="First-price payment; second-price payment; bid-shading benchmark; learned bid-curve output; format-by-format summary table.",
        repo_metrics="Auction House first_price and second_price learned bid curves; outputs/auction_house_full.",
        failures="No learned bid-curve inspection; using revenue alone to rank formats; no reserve/no-sale semantics; no benchmark-case tests.",
        comparison="Compare {title} to Auction House Q-learning full outputs. The repo has the right diagnostics for bidder behavior, but cross-mind auction claims remain pending until full ladder runs are interpreted.",
    ),
    "repeated_auctions": _economic_template(
        institution="Repeated auction learning protocol.",
        agent_type="Learning bidders.",
        theoretical_benchmark="Repeated strategic learning can diverge from one-shot auction predictions.",
        learning_setup="Repeated independent value draws with policy updates and final-window bid curves.",
        metrics="Learning dynamics, final-window revenue/efficiency/regret, bid shading, convergence behavior.",
        reproduce="Treat Auction House as a repeated-learning environment and report final-window summaries plus learned bid curves.",
        differs="The paper focuses on repeated auction learning. This repo uses repeated auctions as one world in a larger institution/capability platform.",
        obligations="Fresh private values per episode; bidder observation includes own valuation; final-window summary; bid-curve extraction by valuation bin.",
        repo_metrics="worlds/auction_house/training.py; outputs/auction_house_full/bid_curves.csv.",
        failures="One-shot benchmark claimed as learned convergence; no final-window separation; no bid curve; changing valuation distribution across scenarios without noting it.",
        comparison="Compare {title} to Auction House training outputs. The repo should interpret auction behavior dynamically, not only as one-shot mechanism theory.",
    ),
    "public_goods_theory": _economic_template(
        institution="No-institution public goods baseline.",
        agent_type="Contributors/extractors or public-good participants.",
        theoretical_benchmark="Private free-riding versus social-optimum contribution/provision brackets.",
        learning_setup="Repeated contribution/extraction decisions with a public pool and learned policies.",
        metrics="Contribution rate, extraction rate, welfare, sustainability, collapse indicators.",
        reproduce="Report free-rider and social-optimum brackets and show whether learned agents underprovide contributions.",
        differs="The theory paper is classical public economics. The repo implements a dynamic commons/public-goods environment with learning agents and institutions.",
        obligations="Free-rider bracket; social optimum bracket; contribution/extraction accounting; pool sustainability; final-window summaries.",
        repo_metrics="worlds/public_goods/benchmarks.py; outputs/public_goods_full/summary_aggregate.csv.",
        failures="Reward-only welfare without state sustainability; no free-rider reference; no contribution metric; treating low sustainability as unexplained noise.",
        comparison="Compare {title} to Public Goods benchmarks and full outputs. Baseline low contribution/sustainability should be interpreted against free-rider theory.",
    ),
    "collective_action": _economic_template(
        institution="No-institution collective-action baseline.",
        agent_type="Self-interested group members / learning agents.",
        theoretical_benchmark="Group benefit does not guarantee individual contribution; free-rider incentives dominate absent institutions.",
        learning_setup="Repeated public-goods/commons interaction with private reward incentives.",
        metrics="Contribution, extraction, sustainability, welfare, group outcome versus individual incentive.",
        reproduce="Explain why low contribution is expected under private incentives and do not treat it as a bug without checking incentives.",
        differs="The book is broad collective-action theory. This repo operationalizes one narrow dynamic public-pool version for learning agents.",
        obligations="Private payoff mapping; public benefit mapping; contribution/extraction metrics; institution comparisons against baseline.",
        repo_metrics="baseline extraction/contribution/sustainability metrics; outputs/public_goods_full.",
        failures="Assuming agents should contribute because welfare would improve; no individual payoff explanation; interpreting low contribution as failed learning only.",
        comparison="Compare {title} to Public Goods baseline behavior. The repo should use it to justify the expected commons pressure before judging institutions.",
    ),
    "punishment": _economic_template(
        institution="Penalty schedule / sanctioning institution.",
        agent_type="Public-goods participants or learning agents under sanctions.",
        theoretical_benchmark="Punishment can sustain cooperation but may impose welfare costs.",
        learning_setup="Contribution/extraction decisions with penalties applied to target behavior.",
        metrics="Contribution, sustainability, welfare, penalty incidence, state-change classification.",
        reproduce="Penalty institutions must show whether contributions/sustainability change, not just whether rewards were reduced.",
        differs="The paper studies experimental punishment. This repo tests algorithmic agents under a stylized penalty schedule.",
        obligations="Penalty binding counter or effect validation; contribution response; sustainability response; welfare cost accounting.",
        repo_metrics="validate_public_goods_effects.py; outputs/public_goods_full/institution_effect_validation.json; penalty_schedule rows.",
        failures="Reward penalties with no behavior change; welfare losses misread as institutional success; no baseline comparison threshold.",
        comparison="Compare {title} to penalty_schedule Public Goods outputs. The important question is whether sanctions alter state behavior, not only accounting rewards.",
    ),
    "conditional_cooperation": _economic_template(
        institution="Reputation and information variants.",
        agent_type="Conditional cooperators or learning agents reacting to observed social information.",
        theoretical_benchmark="Contribution can depend on beliefs/observations about others' contributions.",
        learning_setup="Repeated public-goods interaction with reputation or restricted/shared information.",
        metrics="Contribution response, sustainability, welfare, reputation bonuses, information-condition deltas.",
        reproduce="Information/reputation variants should be judged by contribution response and sustainability, not only reward bonuses.",
        differs="The paper studies human conditional cooperation. This repo tests whether stylized information/reputation hooks create analogous state changes in learners.",
        obligations="Observable contribution/reputation signal; information restriction transform; contribution and sustainability deltas; accounting-vs-state classification.",
        repo_metrics="Public Goods reputation and information_restriction outputs; institution-effect validation.",
        failures="Reputation increases reward without changing contribution; information restriction changes observation label only; no measured state delta.",
        comparison="Compare {title} to Public Goods reputation and information-restriction rows. The repo should separate reward shaping from actual cooperative behavior.",
    ),
    "rewards_sanctions": _economic_template(
        institution="Contribution matching and penalty/reward schedules.",
        agent_type="Public-goods participants / learning agents.",
        theoretical_benchmark="Rewards and sanctions can change provision but may be costly or crowd out intrinsic incentives.",
        learning_setup="Repeated contribution/extraction with externally modified rewards or penalties.",
        metrics="Welfare, contribution, sustainability, reward payments, penalty costs, state-change classification.",
        reproduce="Separate welfare-improving cooperation from costly reward accounting under contribution matching and sanctions.",
        differs="The paper studies experimental reward/sanction provision. This repo uses parameterized institutions and validates state metrics.",
        obligations="Contribution matching transfer accounting; penalty accounting; contribution/sustainability metrics; explicit state-changing versus reward-only classification.",
        repo_metrics="Public Goods institution-effect validator; outputs/public_goods_full.",
        failures="Counting transfers as welfare gains without state change; no cost accounting; no classification of institution effects.",
        comparison="Compare {title} to Public Goods contribution_matching and penalty_schedule rows. The repo should report whether state variables move, not just total reward.",
    ),
    "networked_public_goods": _economic_template(
        institution="Information restriction / networked observability.",
        agent_type="Public-goods participants under limited or networked information.",
        theoretical_benchmark="Network structure and observability affect cooperation contagion and contribution dynamics.",
        learning_setup="Repeated public-goods game where observations restrict or expose social information.",
        metrics="Contribution, sustainability, welfare, information-condition deltas, variance across seeds.",
        reproduce="Treat information restrictions as strategic observability changes and report whether contribution/sustainability differs from baseline.",
        differs="The paper studies networked human experiments. The repo implements a simple information restriction, not a full social network.",
        obligations="Observation transform; baseline comparison; contribution/sustainability deltas; note absence of explicit network topology unless added.",
        repo_metrics="information_restriction institution and contribution/sustainability deltas in Public Goods outputs.",
        failures="Calling an observation mask a network experiment; no state metric movement; no variance/seed reporting.",
        comparison="Compare {title} to information_restriction Public Goods outputs. The repo can use it as an observability anchor with a clear simplification caveat.",
    ),
    "commons": _economic_template(
        institution="No-institution common-pool resource baseline.",
        agent_type="Resource users / spatial learning agents.",
        theoretical_benchmark="Open-access common resources face depletion pressure when private extraction benefits exceed shared costs.",
        learning_setup="Spatial resource gathering/trading with energy, inventories, regeneration, and learned policies.",
        metrics="Resource sustainability, survival, welfare, extraction/gathering, trade, inequality, specialization.",
        reproduce="Resource Island must report depletion/sustainability and activation diagnostics, not only agent reward.",
        differs="The essay is a broad commons warning. The repo implements a stylized spatial inventory world to test whether institutions bind under learning agents.",
        obligations="Sustainability metric; survival metric; gather/trade counters; regeneration accounting; institution activation diagnostics.",
        repo_metrics="resource_sustainability, survival, gather/trade diagnostics; Resource Island v0/v1 full outputs.",
        failures="High survival despite depleted resources not explained; institutions inactive but interpreted as ineffective; whole-island trade treated as spatial trade without caveat.",
        comparison="Compare {title} to Resource Island outputs. The repo's useful contribution is diagnostic: when institutions do not bind, the design reason must be measured.",
    ),
    "common_pool_governance": _economic_template(
        institution="Property rights and reputation governance.",
        agent_type="Common-pool resource users / learning agents.",
        theoretical_benchmark="Governance works through boundaries, monitoring, graduated sanctions, and local rule fit.",
        learning_setup="Spatial resource world with property claims, reputation bonuses, trading, and contested resources.",
        metrics="Property opportunity counts, property violations, trade counts, welfare, sustainability, survival, inequality.",
        reproduce="Property/reputation mechanisms must have activation diagnostics before welfare differences are interpreted.",
        differs="The book studies real common-pool institutions. The repo tests narrow institutional hooks and must not claim full Ostrom governance from simple counters.",
        obligations="Property claim counter; non-owner opportunity counter; violation counter; reputation/trade counter; activation thresholds; v1 contested layouts.",
        repo_metrics="Resource Island v1 property opportunities, violations, and trade diagnostics; outputs/resource_island_v1_full.",
        failures="Zero violations interpreted as success when no opportunity existed; reputation bonus without trade activation; no contested resource pressure.",
        comparison="Compare {title} to Resource Island v1 outputs. The repo is strong where it reports activation pressure before interpreting institution effects.",
    ),
    "design_principles": _economic_template(
        institution="Natural-resource governance design principles.",
        agent_type="Resource users / institution-governed learning agents.",
        theoretical_benchmark="Operational design principles: boundaries, monitoring, sanctioning, conflict resolution, and local fit.",
        learning_setup="Stylized Resource Island v1 layouts that create contested resources and measurable institution pressure.",
        metrics="Activation thresholds, property opportunities/violations, trade blocks, sustainability, welfare, survival.",
        reproduce="Check monitoring, boundaries, sanctions, and local incentive conditions through explicit v1 diagnostics.",
        differs="The paper reviews field governance principles. The repo implements minimal test hooks and should use the paper as a checklist, not as a validation claim.",
        obligations="Contested resource layout; measurable non-owner opportunities; trade-price-control binding; reputation effects; explicit caveats for missing real governance features.",
        repo_metrics="Resource Island v1 contested layouts and activation thresholds; outputs/resource_island_v1_full.",
        failures="Treating v0 inactive property rights as evidence; lacking monitoring/opportunity counters; price controls unable to bind due to one-for-one trades.",
        comparison="Compare {title} to Resource Island v1 hardening. The repo has begun satisfying activation obligations but still lacks full institutional richness.",
    ),
    "sequential_social_dilemmas": _economic_template(
        institution="Sequential social-dilemma institutions across resource/public-goods worlds.",
        agent_type="Deep MARL agents in temporally extended social dilemmas.",
        theoretical_benchmark="Cooperation and defection emerge over time through spatial/temporal coordination, not one-shot payoffs only.",
        learning_setup="Sequential interaction with resource dynamics, partial observability, and multi-agent learning.",
        metrics="Cooperation/trade/contribution, sustainability, welfare, survival, coordination failures, robustness.",
        reproduce="Frame failed trade/institution activation as coordination/exploration evidence and report attempts versus successes.",
        differs="The paper develops sequential social-dilemma framing. The repo applies a smaller version to Resource Island and Public Goods with explicit diagnostics.",
        obligations="Attempt counters; success counters; inventory/block reasons; final-window welfare/survival; cross-mind ladder table.",
        repo_metrics="Resource Island P.6 full trade-attempt and success diagnostics; Public Goods full outputs.",
        failures="Claiming strategic avoidance when agents never attempted the cooperative action; no attempt/block breakdown; no horizon/exploration caveat.",
        comparison="Compare {title} to Resource Island cross-mind results. The safe thesis claim is coordination/exploration failure under current training, not proof that stronger agents reject trade.",
    ),
    "social_preferences": _economic_template(
        institution="Redistribution, reputation, and social-preference reward modifications.",
        agent_type="Deep MARL agents with modified incentives.",
        theoretical_benchmark="Social-preference shaping can improve cooperation in intertemporal dilemmas.",
        learning_setup="Sequential dilemmas with reward modifications for equity, reputation, or cooperation.",
        metrics="Cooperation/trade/contribution, welfare, inequality, sustainability, reward-accounting versus state changes.",
        reproduce="When institutions change rewards, check whether they alter state behavior or only accounting.",
        differs="The paper studies social-preference shaping. The repo uses simpler redistribution/reputation/tax hooks and must classify state versus reward effects.",
        obligations="State metrics and reward metrics side by side; inequality metric; contribution/trade metrics; effect classification.",
        repo_metrics="Resource Island and Public Goods welfare versus state-metric comparisons; tax_schedule_sweep outputs.",
        failures="Reward shaping presented as cooperation when state variables do not move; no inequality metric; no baseline/no-tax comparison.",
        comparison="Compare {title} to redistribution, reputation, and tax outputs. The repo should be explicit about accounting-only effects.",
    ),
    "marl_benchmark": _economic_template(
        institution="Cross-world social-dilemma benchmark discipline.",
        agent_type="Multi-agent RL agents evaluated across tasks.",
        theoretical_benchmark="Generalization and robustness require held-out tasks/populations, not only in-distribution performance.",
        learning_setup="Multiple social dilemma scenarios with train/test variation and agent-population evaluation.",
        metrics="Generalization, robustness, welfare, cooperation, exploitation, held-out scenario performance.",
        reproduce="Do not claim general social robustness from in-distribution training alone; use cross-world synthesis and future held-out variants.",
        differs="The benchmark suite is much broader. This repo has fewer worlds but uses explicit economic institutions and classical benchmarks.",
        obligations="Cross-world synthesis; mechanism taxonomy; held-out variants as future work; no overclaim from one-world success.",
        repo_metrics="Cross-world synthesis outputs; future held-out institution/world variants.",
        failures="Five worlds reported as five isolated tables; no synthesis; generalization claims without held-out tests.",
        comparison="Compare {title} to build_cross_world_synthesis.py outputs. The repo can become benchmark-like only if the synthesis, not just world count, is thesis-facing.",
    ),
    "stable_matching": _economic_template(
        institution="Deferred-acceptance matching.",
        agent_type="Workers/students and employers/colleges with preferences.",
        theoretical_benchmark="Deferred acceptance produces stable matchings with no blocking pairs under truthful preferences.",
        learning_setup="Workers report top choices or rankings; employers have fixed preferences; matching is computed by deferred acceptance.",
        metrics="Match rate, stability, blocking pairs, welfare, truthful-report rate, manipulation diagnostics.",
        reproduce="Verify matching validity and blocking-pair stability before interpreting learned reports.",
        differs="The paper gives matching theory. This repo lets learning agents report preferences and measures whether outcomes stay stable.",
        obligations="Valid matching; no duplicate assignments; blocking-pair detection; side-proposing semantics; truthful benchmark cases.",
        repo_metrics="worlds/labor_market/benchmarks.py; outputs/labor_market_full stability metrics.",
        failures="Full match rate mistaken for stability; no blocking-pair check; side-proposing mechanism unspecified; asymmetric agents forced into symmetric MARL assumptions.",
        comparison="Compare {title} to Labor Market benchmark cases and full outputs. Stability, not just match rate, is the theory obligation.",
    ),
    "incentives": _economic_template(
        institution="Deferred acceptance with incentive constraints.",
        agent_type="Workers/students and employers/colleges with strategic reports.",
        theoretical_benchmark="Deferred acceptance is strategy-proof for the proposing side under standard assumptions but not for both sides.",
        learning_setup="Agents learn or choose reported preferences under a fixed matching protocol.",
        metrics="Truthful-report rate, manipulation gain, stability, welfare, side-specific profitable deviations.",
        reproduce="Do not interpret worker-side misreport profits under worker-proposing DA as expected theory; test side-specific incentives.",
        differs="The paper establishes incentive limits of stable matching. The repo currently has learning workers and fixed employer preferences, so incentive claims are side-specific.",
        obligations="State proposing side; enumerate fixed benchmark deviations; manipulation-gain diagnostics; do not claim two-sided strategy-proofness.",
        repo_metrics="labor_market_benchmark_cases.json; manipulation-gain diagnostics; outputs/labor_market_full.",
        failures="Calling any non-truthful report manipulation without profitable deviation; testing only the strategy-proof side; no fixed preference hand cases.",
        comparison="Compare {title} to Labor Market benchmark cases. The repo should use Roth to avoid false manipulation claims under worker-proposing DA.",
    ),
    "market_design_application": _economic_template(
        institution="Deferred acceptance as applied market-design replacement.",
        agent_type="Students/workers reporting preferences in a matching market.",
        theoretical_benchmark="Mechanism changes can reduce manipulation and improve stability relative to manipulable assignment rules.",
        learning_setup="Reported preferences feed a matching mechanism; learned reports are compared to truthful/stable benchmarks.",
        metrics="Truthfulness, stability, welfare, manipulation gain, blocking pairs.",
        reproduce="Use fixed benchmark cases to separate mechanism manipulation from noisy learned reports.",
        differs="The paper is an applied school-choice reform. This repo abstracts the market to labor-style workers/employers and learning reports.",
        obligations="Canonical preference cases; stable and unstable hand cases; welfare accounting; side-specific strategy-proofness checks.",
        repo_metrics="Labor Market fixed benchmark cases and full-run truthfulness/stability.",
        failures="Random preference variation mistaken for mechanism effect; no fixed cases; no welfare accounting under alternate mechanisms.",
        comparison="Compare {title} to run_labor_market_benchmark_cases.py outputs. The repo has the right fixed-case discipline but should not claim a school-choice reproduction.",
    ),
    "matching_overview": _economic_template(
        institution="Deferred-acceptance mechanism design.",
        agent_type="Two-sided matching participants.",
        theoretical_benchmark="DA properties depend on which side proposes and on preference/information assumptions.",
        learning_setup="Learning/reporting agents operate within an explicitly side-proposing matching protocol.",
        metrics="Stability, match rate, truthfulness, manipulation gain, welfare.",
        reproduce="State which side proposes and what strategy-proofness claim is valid.",
        differs="The overview bridges theory/practice. The repo must use it to write clear mechanism assumptions, especially before deep RL/MARL on asymmetric agents.",
        obligations="Design document states roles and proposer; benchmark cases verify claims; asymmetric-agent caveat for centralized critic.",
        repo_metrics="Labor Market DESIGN.md and benchmark cases.",
        failures="Vague DA label; hidden proposer side; matching claims independent of side/information assumptions.",
        comparison="Compare {title} to worlds/labor_market/DESIGN.md and benchmark outputs. The repo should make mechanism assumptions explicit before synthesis.",
    ),
    "learning_matching": _economic_template(
        institution="Learning in matching markets.",
        agent_type="RL agents in Markov or repeated matching markets.",
        theoretical_benchmark="Learning-market performance should report regret/stability together, not reward alone.",
        learning_setup="Dynamic matching with learned strategies over repeated market states.",
        metrics="Regret, stability, welfare, match rate, manipulation, convergence.",
        reproduce="If using deep RL in Labor Market, report regret/stability jointly and handle worker/employer asymmetry explicitly.",
        differs="The paper is closest to future Labor Market P.6. This repo has Q-learning full runs now; deep RL Labor Market ladder is a pending asymmetric-agent stress test.",
        obligations="Regret or manipulation proxy; stability; side-specific observations/actions; asymmetric-agent support for centralized critic; full n=20 ladder before thesis claims.",
        repo_metrics="Future Labor Market P.6 full ladder and synthesis; current labor_market_full and benchmark cases.",
        failures="Reward-only deep RL matching table; centralized critic assumes symmetric agents; no side-specific regret/stability report.",
        comparison="Compare {title} to the Labor Market roadmap and future P.6 outputs. It defines the standard the repo must meet before deep-RL matching claims are made.",
    ),
}


TEMPLATE_FIELD_KEYS = (
    "institution",
    "agent_type",
    "theoretical_benchmark",
    "learning_setup",
    "metrics",
    "what_we_need_to_reproduce",
    "how_our_project_differs",
    "implementation_obligations",
    "metrics_to_compare_in_our_repo",
    "failure_modes_to_audit",
    "project_code_comparison",
)


def apply_obligation_template(fields: dict[str, Any], record: dict[str, Any]) -> bool:
    role = str(record.get("role") or "").strip()
    template = ROLE_TEMPLATES.get(role)
    if template is None:
        return False
    fields.update(template.to_fields(record))
    return True
