from __future__ import annotations

import csv
import re
from dataclasses import dataclass
from pathlib import Path

from .fill_paper_cards import parse_markdown_sections


WORLD_NAMES = {
    "pricing_arena": "Pricing Arena",
    "resource_island": "Resource Island",
    "auction_house": "Auction House",
    "public_goods": "Public Goods",
    "labor_market": "Labor Market",
}

WORLD_ORDER = [
    "pricing_arena",
    "resource_island",
    "auction_house",
    "public_goods",
    "labor_market",
]


@dataclass(frozen=True)
class FoundationCard:
    path: Path
    title: str
    world: str
    year: str
    confidence: str
    sections: dict[str, str]


def _single_line(text: str, max_chars: int = 520) -> str:
    cleaned = " ".join(str(text or "").replace("\n", " ").split())
    if len(cleaned) <= max_chars:
        return cleaned
    return cleaned[: max_chars - 3].rstrip() + "..."


def _metadata_value(text: str, key: str) -> str:
    match = re.search(rf"^{re.escape(key)}:\s*(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else ""


def _title(text: str, fallback: str) -> str:
    match = re.search(r"^#\s+(.+)$", text, re.MULTILINE)
    return match.group(1).strip() if match else fallback


def load_foundation_cards(cards_dir: Path) -> list[FoundationCard]:
    cards: list[FoundationCard] = []
    if not cards_dir.exists():
        return cards
    for path in sorted(cards_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        sections = parse_markdown_sections(text)
        world = _metadata_value(text, "World") or sections.get("World", "")
        cards.append(
            FoundationCard(
                path=path,
                title=_title(text, path.stem),
                world=world.strip(),
                year=_metadata_value(text, "Year"),
                confidence=(_metadata_value(text, "Confidence") or "unknown").lower(),
                sections=sections,
            )
        )
    return cards


def load_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open(encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle))


def _unique_nonempty(values: list[str], limit: int = 4) -> list[str]:
    seen: set[str] = set()
    out: list[str] = []
    for value in values:
        cleaned = _single_line(value)
        if not cleaned or cleaned.lower() in {"todo", "not stated in supplied text."}:
            continue
        key = cleaned.lower()
        if key in seen:
            continue
        seen.add(key)
        out.append(cleaned)
        if len(out) >= limit:
            break
    return out


def _anchor_lines(cards: list[FoundationCard]) -> list[str]:
    lines = []
    for card in cards:
        year = f"{card.year}: " if card.year else ""
        confidence = f"; confidence={card.confidence}" if card.confidence else ""
        lines.append(f"- {year}{card.title} (`{card.path.as_posix()}`{confidence})")
    return lines or ["- No foundation cards found for this world."]


def _section_bullets(cards: list[FoundationCard], section: str, limit: int = 4) -> list[str]:
    values = _unique_nonempty([card.sections.get(section, "") for card in cards], limit=limit)
    return [f"- {value}" for value in values] or ["- No card-level text available."]


def _novelty_lines(rows: list[dict[str, str]], world: str) -> list[str]:
    world_rows = [row for row in rows if row.get("world") == world]
    by_gap = _unique_nonempty([row.get("gap", "") for row in world_rows], limit=3)
    return [f"- {gap}" for gap in by_gap] or ["- No novelty rows found for this world."]


def build_world_obligation_bridge(
    *,
    cards_dir: Path,
    theory_gap_report: Path,
    novelty_gap_table: Path,
) -> str:
    cards = load_foundation_cards(cards_dir)
    cards_by_world: dict[str, list[FoundationCard]] = {}
    for card in cards:
        cards_by_world.setdefault(card.world, []).append(card)

    gap_rows = {row.get("world", ""): row for row in load_csv_rows(theory_gap_report)}
    novelty_rows = load_csv_rows(novelty_gap_table)
    worlds = [world for world in WORLD_ORDER if world in gap_rows or world in cards_by_world]

    lines = [
        "# Theory Obligations By World",
        "",
        "Generated by `python -m tools.theory_scout.cli world-obligation-bridge`.",
        "",
        "This is the writing bridge between the literature cards and the experiments.",
        "It is intentionally not a related-work dump. Each world must answer:",
        "",
        "1. What is the classical benchmark?",
        "2. What is the known RL/MARL result?",
        "3. What metric obligation follows from that literature?",
        "4. What does the repo reproduce or validate?",
        "5. What does the repo add?",
        "6. What can the repo still not claim?",
        "",
        "Canonical inputs:",
        "",
        f"- Foundation cards: `{cards_dir.as_posix()}`",
        f"- Theory gap report: `{theory_gap_report.as_posix()}`",
        f"- Novelty table: `{novelty_gap_table.as_posix()}`",
        "",
    ]

    for world in worlds:
        display = WORLD_NAMES.get(world, world)
        world_cards = cards_by_world.get(world, [])
        gap = gap_rows.get(world, {})
        lines.extend([f"## {display}", ""])
        lines.extend(["### Foundation Anchors", "", *_anchor_lines(world_cards), ""])
        lines.extend(
            [
                "### Classical Benchmark",
                "",
                _single_line(gap.get("classical_prediction", "No classical prediction found.")),
                "",
                f"Benchmark to reproduce: {_single_line(gap.get('benchmark_to_reproduce', 'No benchmark found.'))}",
                "",
                "Card-level benchmarks:",
                "",
                *_section_bullets(world_cards, "Theoretical benchmark", limit=4),
                "",
                "### Known RL/MARL Result",
                "",
                _single_line(gap.get("known_rl_marl_result", "No RL/MARL precedent found.")),
                "",
                "Card-level learning setups/results:",
                "",
                *_section_bullets(world_cards, "Main result", limit=4),
                "",
                "### Metric Obligation",
                "",
                f"Prior metrics: {_single_line(gap.get('prior_metric', 'No prior metrics found.'))}",
                "",
                f"Our metrics: {_single_line(gap.get('our_metric', 'No repo metrics found.'))}",
                "",
                "Repo metric/code targets from cards:",
                "",
                *_section_bullets(world_cards, "Metrics to compare in our repo", limit=4),
                "",
                "### What Our Code Reproduces Or Validates",
                "",
                *_section_bullets(world_cards, "Project code comparison", limit=4),
                "",
                "### What Our Result Adds",
                "",
                f"World-level gap: {_single_line(gap.get('remaining_gap', 'No remaining-gap row found.'))}",
                "",
                "Novelty table signals:",
                "",
                *_novelty_lines(novelty_rows, world),
                "",
                "### What This World Still Cannot Claim",
                "",
                "Failure modes to audit:",
                "",
                *_section_bullets(world_cards, "Failure modes to audit", limit=4),
                "",
                "Paper-side omitted tests:",
                "",
                *_section_bullets(world_cards, "What they do NOT test", limit=4),
                "",
                "### Claim Sentence",
                "",
                (
                    f"This result is reportable because {display} reproduces or brackets "
                    f"`{_single_line(gap.get('benchmark_to_reproduce', 'benchmark'), 180)}`, "
                    f"measures `{_single_line(gap.get('our_metric', 'metrics'), 180)}`, and audits the failure modes above; "
                    f"the novel claim is `{_single_line(gap.get('remaining_gap', 'gap'), 180)}`, while the listed boundaries remain outside the claim."
                ),
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def write_world_obligation_bridge(
    *,
    cards_dir: Path,
    theory_gap_report: Path,
    novelty_gap_table: Path,
    out_path: Path,
) -> str:
    text = build_world_obligation_bridge(
        cards_dir=cards_dir,
        theory_gap_report=theory_gap_report,
        novelty_gap_table=novelty_gap_table,
    )
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(text, encoding="utf-8")
    return text
