#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

mkdir -p literature
secrets_file="literature/secrets.env"

read -r -p "OpenAlex API key (blank to skip): " openalex_key
read -r -p "OpenAlex mailto/email (blank to skip): " openalex_mailto
read -r -s -p "Semantic Scholar API key (blank to skip): " semantic_key
printf '\n'
read -r -p "Unpaywall email (blank to skip): " unpaywall_email

umask 077
{
  printf '# Local theory-scout secrets. Ignored by git.\n'
  printf '# Generated by scripts/configure_theory_scout_secrets.sh\n'
  [[ -n "$openalex_key" ]] && printf 'export OPENALEX_API_KEY=%q\n' "$openalex_key"
  [[ -n "$openalex_mailto" ]] && printf 'export OPENALEX_MAILTO=%q\n' "$openalex_mailto"
  [[ -n "$semantic_key" ]] && printf 'export SEMANTIC_SCHOLAR_API_KEY=%q\n' "$semantic_key"
  [[ -n "$unpaywall_email" ]] && printf 'export UNPAYWALL_EMAIL=%q\n' "$unpaywall_email"
} > "$secrets_file"

chmod 600 "$secrets_file"
printf 'Wrote %s with mode 600. Values are not echoed here.\n' "$secrets_file"
