#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."
mkdir -p outputs/post_run_diagnostics outputs/logs

export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"
export TORCH_NUM_THREADS="${TORCH_NUM_THREADS:-1}"
export PYTHONUNBUFFERED=1

python_bin=".venv/bin/python"
if [[ ! -x "$python_bin" ]]; then
  python_bin="python3"
fi

timestamp() {
  date --iso-8601=seconds
}

run_step() {
  local name="$1"
  shift
  local log_path="outputs/logs/post_run_diagnostics_${name}.log"
  echo "[$(timestamp)] START ${name}" | tee -a "$log_path"
  "$@" 2>&1 | tee -a "$log_path"
  echo "[$(timestamp)] DONE ${name}" | tee -a "$log_path"
}

run_step known_answers \
  "$python_bin" run_known_answer_sanity_checks.py \
    --save-dir outputs/post_run_diagnostics/known_answer_sanity_checks

run_step traces_all_worlds_n2 \
  "$python_bin" run_mechanism_traces.py \
    --worlds all \
    --minds all \
    --steps 5000 \
    --final-window 1000 \
    --max-trace-rows 1000 \
    --n-agents 2 \
    --save-dir outputs/post_run_diagnostics/mechanism_traces_all_worlds_n2

run_step traces_pricing_n5 \
  "$python_bin" run_mechanism_traces.py \
    --worlds pricing_arena \
    --minds q_learning dqn ppo independent_dqn centralized_critic \
    --steps 5000 \
    --final-window 1000 \
    --max-trace-rows 1000 \
    --n-agents 5 \
    --save-dir outputs/post_run_diagnostics/mechanism_traces_pricing_n5

run_step traces_public_goods_n8 \
  "$python_bin" run_mechanism_traces.py \
    --worlds public_goods \
    --minds q_learning dqn ppo independent_dqn centralized_critic \
    --steps 5000 \
    --final-window 1000 \
    --max-trace-rows 1000 \
    --n-agents 8 \
    --save-dir outputs/post_run_diagnostics/mechanism_traces_public_goods_n8

cat > outputs/post_run_diagnostics/README.md <<'EOF'
# Post-Run Diagnostics

Generated by `scripts/run_post_run_diagnostics.sh`.

This folder is the queued theory-contact/mechanism-trace layer to run after
the long N-sensitive sweeps finish:

- `known_answer_sanity_checks/`: exact theorem/bracketing checks.
- `mechanism_traces_all_worlds_n2/`: all five worlds x all thesis-facing minds.
- `mechanism_traces_pricing_n5/`: N-firm price-cap quantity/margin trace.
- `mechanism_traces_public_goods_n8/`: group-size commons contribution/extraction trace.

These outputs are diagnostics for writing and mechanism interpretation. They
do not replace the n=20 full-run tables.
EOF

echo "[$(timestamp)] post-run diagnostics complete"
